In [1]:
import pandas as pd
import datetime as dt
import plotly.graph_objects as go
from technicals.indicators import *
from technicals.patterns import apply_patterns
from technicals.patternsInRange import apply_patterns_in_range
from guruTester import GuruTester,GuruTester2
from plotting import CandlePlot
import MetaTrader5 as mt5
from datetime import datetime
from getCandle import Rates
from sklearn.neural_network import MLPClassifier
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler  
import pickle
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

In [2]:
def featureExtraction(df):
    candle_patterns = ['HANGING_MAN', 'SHOOTING_STAR',
           'SPINNING_TOP', 'MARUBOZU', 'ENGULFING', 'TWEEZER_TOP',
           'TWEEZER_BOTTOM', 'MORNING_STAR', 'EVENING_STAR']
    df = apply_patterns_in_range(df)
    for cp in candle_patterns:
        df[cp] = df[cp].astype(float)

    df = BollingerBandsNonLinear(df)
#     df = ATRFeature(df)
    df = KeltnerChannelsNonLinear(df)
    df = RSINonLinear(df)
    df = MACDNonLinear(df)
    df = BREAKOUT(df)
    df = ichimokuNonLinear(df)

    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

    return df

In [30]:
BUY = 2
SELL = 0
NONE = 1

In [31]:
PROFIT_FACTOR = 1.2
def labeling(df):
    df['SIGNAL_LABEL'] = NONE
    df['TP'] = 0
    df['SL'] = 0
    
    for i in tqdm(range(1,len(df)) ):
        for j in range(i,len(df)):
            if( df.low[j] <= df.low[i-1] ):
                break
            else:
                if(df.high[j] > PROFIT_FACTOR*(df.close[i] - df.low[i-1] ) + df.close[i]):
                    df.SIGNAL_LABEL[i] = BUY
                    break


        for j in range(i,len(df)):
            if( df.high[j] >= df.high[i-1] ):
                break
            else:
                if(df.low[j] < PROFIT_FACTOR*(df.close[i] - df.high[i-1] ) + df.close[i]):
                    df.SIGNAL_LABEL[i] = SELL
                    break

        
    return df

In [32]:
pairs = ["GBPUSD","EURUSD","USDCHF","USDCAD","EURCHF"]
NB_H1_CANDLES = 20000

In [33]:
all_data = {}
for pair in pairs:
    rates = Rates(pair, NB_H1_CANDLES, mt5.TIMEFRAME_H1)
    SPREAD = rates.get_spread()
    df_an = rates.get_rates_from_now()
    df_an.drop(NB_H1_CANDLES-1,inplace=True) 
    df_an.drop(['tick_volume', 'spread', 'real_volume'], axis=1, inplace=True)
    all_data[pair] = df_an
    

In [34]:
SPREAD = (SPREAD//1e-5)*1e-5 # todo: do it right!!!
SPREAD # 0

0.00011

In [35]:
all_data_train = {}
all_data_test = {}
for pair in pairs:
    SLIT_INDEX = int(0.8*len(all_data[pair]))
    all_data_train[pair] = all_data[pair].iloc[:SLIT_INDEX]
    all_data_train[pair].reset_index(drop=True, inplace=True)
    all_data_test[pair] = all_data[pair].iloc[SLIT_INDEX:]
    all_data_test[pair].reset_index(drop=True, inplace=True)

In [36]:
all_data.keys()

dict_keys(['GBPUSD', 'EURUSD', 'USDCHF', 'USDCAD', 'EURCHF'])

In [37]:
# rates = Rates(pair, 13*len(df_test), mt5.TIMEFRAME_M5)
# df_m5 = rates.get_rates_from_now()
# df_m5.reset_index(drop=True, inplace=True)
# df_m5.drop(['tick_volume', 'spread', 'real_volume'], axis=1, inplace=True)

In [38]:
for pair in pairs:
    all_data_train[pair] = featureExtraction(all_data_train[pair])
    all_data_train[pair] = labeling(all_data_train[pair])
    all_data_test[pair] = featureExtraction(all_data_test[pair])
    all_data_test[pair] = labeling(all_data_test[pair])


C:\Users\meysam\Desktop\algotramic\technicals\indicators.py:215: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_pivot_h'].iloc[i] = last_pivot_h
C:\Users\meysam\Desktop\algotramic\technicals\indicators.py:216: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_pivot_l'].iloc[i] = last_pivot_l
  0%|                                                                                        | 0/15917 [00:00<?, ?it/s]C:\Users\meysam\AppData\Local\Temp\ipykernel_11252\2628886360.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: ht

  0%|                                                                                         | 0/3921 [00:00<?, ?it/s]C:\Users\meysam\AppData\Local\Temp\ipykernel_11252\2628886360.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.SIGNAL_LABEL[i] = SELL
C:\Users\meysam\AppData\Local\Temp\ipykernel_11252\2628886360.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.SIGNAL_LABEL[i] = BUY
100%|█████████████████████████████████████████████████████████████████████████████| 3921/3921 [00:08<00:00, 437.63it/s]
C:\Users\meysam\Desktop\algotramic\technicals\indicators.py:215: SettingWithCopyWarning: 
A value is tryin

In [39]:

feature_col = [
    'BB_MA_cross', 'BB_UP_touch','BB_LW_touch',
    'EMA_cross', 'KeUp_touch', 'KeLo_touch', 
    'RSI_level',
    'MACDHIST_level',
#      'BREAK_UP', 'BREAK_DOWN',
        'Tenkan_sen_touch', 'Kijun_sen_touch',
       'Senkou_Span_A_touch', 'Senkou_Span_B_touch',
        'Ten_kij_cross','Cloud_cross',
#         'full_range',# this is added ...
#        'body_lower', 'body_upper', 
#         'body_bottom_perc', 'body_top_perc',
#        'body_perc', 'direction', 'body_size', 'low_change', 'high_change',
#     'mid_point', 'mid_point_prev_2', 'body_size_prev',
#        'direction_prev', 'direction_prev_2', 'body_perc_prev','body_perc_prev_2',
        'direction',
        'HANGING_MAN', 'SHOOTING_STAR', 'SPINNING_TOP',
       'MARUBOZU', 'ENGULFING',
    'TWEEZER_TOP', 'TWEEZER_BOTTOM',
       'MORNING_STAR', 'EVENING_STAR'
]

In [40]:
class RNN(nn.Module):
    def __init__(self, batch_size, input_size, hidden_dim,lstm_layers):
        super(RNN, self).__init__()
        self.input_size = input_size
        self.batch_size = batch_size
        self.hidden_dim = hidden_dim
        self.LSTM_layers = lstm_layers
    
        self.dropout = nn.Dropout(0.5)
        self.rnn = nn.GRU(input_size=input_size, hidden_size=self.hidden_dim, num_layers=self.LSTM_layers, batch_first=True)
        self.fc1 = nn.Linear(in_features=self.hidden_dim, out_features=self.hidden_dim)
        self.fc2 = nn.Linear(in_features=self.hidden_dim, out_features=3)
#         self.fc2 = nn.Linear(257, 1)

    def forward(self, x):
        h = torch.zeros((self.LSTM_layers, x.size(0), self.hidden_dim))
#         c = torch.zeros((self.LSTM_layers, x.size(0), self.hidden_dim))
#         torch.nn.init.xavier_normal_(h)
#         torch.nn.init.xavier_normal_(c)
        out, _ = self.rnn(x, h)
#         out = self.dropout(out)
        out = torch.relu_(self.fc1(out[:,-1,:]) )
#         out = self.dropout(out)
        out = self.fc2(out)
        return out

In [41]:
class dataset(Dataset):
    def __init__(self,all_data,sequence_lenght,feature_col):
        self.all_data = all_data
        self.sequence_lenght = sequence_lenght
        self.feature_col = feature_col
        self.X = []
        self.Y = [] 
        self.indeces = []
        print("preparing data..")
        self.prepare_data()
        
    def prepare_data(self):
        for pair in self.all_data.keys():
            for i in tqdm(range(self.sequence_lenght+1,len(self.all_data[pair])) ):
    #             if self.df.pivots_h[i-1] or self.df.pivots_l[i-1]:
                X_feat = [] 
                for j in range(self.sequence_lenght):
                    feature = []
                    feature.append(self.all_data[pair].pivots_h[i-self.sequence_lenght+j])
                    feature.append(self.all_data[pair].pivots_l[i-self.sequence_lenght+j])
                    for fc in self.feature_col:
                        feature.append(self.all_data[pair][fc][i-self.sequence_lenght+j+1])

                    X_feat.append(feature)  
                self.X.append(np.array(X_feat))# TODO: use torch tensor 
                self.Y.append(self.all_data[pair].SIGNAL_LABEL[i])
                self.indeces.append(i)
                
    def get_feature_len(self):
        return self.X[0].shape[1]
    
    def __len__(self):
        return len(self.Y)
    
    def __getitem__(self,index):
        return torch.from_numpy(self.X[index]).float(),self.Y[index]

In [42]:
epoch = 1000
batch_size = 600
sequence_lenght = 20

In [43]:
ds_train = dataset(all_data_train,sequence_lenght,feature_col)
ds_test = dataset(all_data_test,sequence_lenght,feature_col) 

preparing data..


100%|███████████████████████████████████████████████████████████████████████████| 15881/15881 [02:11<00:00, 120.82it/s]


preparing data..


100%|█████████████████████████████████████████████████████████████████████████████| 3901/3901 [00:30<00:00, 127.26it/s]


In [44]:
loader_train = DataLoader(ds_train, batch_size=batch_size,shuffle=True)
loader_test = DataLoader(ds_test, batch_size=batch_size,shuffle=False)

In [45]:
print(len(loader_train))
print(len(loader_test))
print(len(ds_train))
print(len(ds_test))

133
33
79464
19505


In [46]:
ds_train.get_feature_len() 

26

In [47]:
input_size = ds_train.get_feature_len() 
hidden_dim = 60
lstm_layers = 2

In [48]:
model = RNN(batch_size, input_size, hidden_dim,lstm_layers)

In [49]:
weight = torch.Tensor([0.45,0.1,0.45])

In [50]:
criterion = nn.CrossEntropyLoss(weight=weight)
# criterion = nn.CrossEntropyLoss()

In [51]:
optimizer = optim.Adam(model.parameters(),lr=1e-3)

In [ ]:
model.train()
train_loss = []
test_loss = []
test_accuracy = []
for i in range(epoch):
    loss_epoch_train = 0
    for x_batch, y_batch in tqdm(loader_train):
        pred = model(x_batch)
        loss = criterion(pred,y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        loss_epoch_train += loss.detach().item()
        
    
    loss_epoch_test = 0
    model.eval()
    pred_test = []
    all_label = []
    
    for x_batch, y_batch in tqdm(loader_test):
        pred = model(x_batch)
        loss = criterion(pred,y_batch)
        loss_epoch_test += loss.detach().item()
        pred_test += list(pred.softmax(dim=1).argmax(dim=1).detach().numpy())
        all_label += list(y_batch.detach().numpy())
        
    train_loss.append(loss_epoch_train/len(loader_train))
    test_loss.append(loss_epoch_test/len(loader_test))
    pred_test = np.array(pred_test)
    all_label = np.array(all_label)
    conf = confusion_matrix(all_label, pred_test)
    acc_buy = conf[2,2]/conf[2,:].sum()
    acc_sell = conf[0,0]/conf[0,:].sum()
    print(conf)
    test_accuracy.append((pred_test==all_label).sum()/len(all_label))
    print(train_loss[-1],test_accuracy[-1],acc_buy,acc_sell)

100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.48it/s]


[[4232    0  969]
 [4486    0 5112]
 [ 642    0 4064]]
0.8780608464004402 0.42532683927198156 0.8635784105397365 0.813689675062488


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.55it/s]


[[4459   59  683]
 [4594  445 4559]
 [ 798   51 3857]]
0.7253772750832981 0.4491668802871059 0.819592010199745 0.857335127860027


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.77it/s]


[[4425  110  666]
 [4358  771 4469]
 [ 736   82 3888]]
0.6781896814367825 0.4657267367341707 0.8261793455163621 0.8507979234762546


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.72it/s]


[[4486   79  636]
 [4369  823 4406]
 [ 739   78 3889]]
0.6595104072327004 0.47157139195078185 0.8263918402039949 0.8625264372236109


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.34it/s]


[[4460   93  648]
 [4309  850 4439]
 [ 747   70 3889]]
0.652164744255238 0.4716226608561907 0.8263918402039949 0.8575273985771967


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.44it/s]


[[4679   49  473]
 [4590  788 4220]
 [ 878   83 3745]]
0.6477962629239362 0.472289156626506 0.7957926051848704 0.8996346856373775


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.78it/s]


[[4609   82  510]
 [4399  849 4350]
 [ 852   62 3792]]
0.6445755886852294 0.47423737503204305 0.8057798555036124 0.8861757354354932


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:08<00:00,  4.09it/s]


[[4578   53  570]
 [4490  849 4259]
 [ 787   91 3828]]
0.6418223761974421 0.4744937195590874 0.8134296642583936 0.8802153432032301


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.91it/s]


[[4569   81  551]
 [4376  872 4350]
 [ 792   66 3848]]
0.6392128642340352 0.47623686234298895 0.8176795580110497 0.8784849067487022


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.79it/s]


[[4488   52  661]
 [4452  881 4265]
 [ 709   84 3913]]
0.636004290186373 0.4758779800051269 0.8314917127071824 0.8629109786579504


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.76it/s]


[[4556   69  576]
 [4343  868 4387]
 [ 806   68 3832]]
0.6342306473201379 0.4745449884644963 0.8142796430089247 0.8759853874254951


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.68it/s]


[[4544   92  565]
 [4230  979 4389]
 [ 818   63 3825]]
0.6323007627537376 0.4792617277621123 0.8127921801954952 0.8736781388194578


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.61it/s]


[[4634   54  513]
 [4557  954 4087]
 [ 853  104 3749]]
0.6304861714965418 0.4786977698026147 0.7966425839354017 0.8909825033647375


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.78it/s]


[[4593   57  551]
 [4465  938 4195]
 [ 804   84 3818]]
0.6275270903917184 0.47931299666752114 0.8113047173820654 0.8830994039607768


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.24it/s]


[[4574   86  541]
 [4384 1157 4057]
 [ 796  135 3775]]
0.6262874661531663 0.48736221481671366 0.8021674458138547 0.8794462603345511


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:08<00:00,  4.06it/s]


[[4653   52  496]
 [4568  863 4167]
 [ 863   68 3775]]
0.6247195278791556 0.4763394001538067 0.8021674458138547 0.8946356469909633


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:08<00:00,  3.84it/s]


[[4531   77  593]
 [4340 1019 4239]
 [ 758   77 3871]]
0.622111051154316 0.4830043578569598 0.8225669358266043 0.8711786194962508


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.31it/s]


[[4662   79  460]
 [4392  981 4225]
 [ 894   69 3743]]
0.6205940797812957 0.48120994616764934 0.7953676158096048 0.8963660834454913


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.48it/s]


[[4694   49  458]
 [4624  861 4113]
 [ 906   67 3733]]
0.6181912901706266 0.4761855934375801 0.7932426689332767 0.902518746394924


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.59it/s]


[[4604   77  520]
 [4409  993 4196]
 [ 856   74 3776]]
0.6177492482321603 0.48054345039733404 0.8023799405014874 0.8852143818496443


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.40it/s]


[[4624   57  520]
 [4436  828 4334]
 [ 834   40 3832]]
0.614734249007433 0.47598051781594464 0.8142796430089247 0.8890597961930398


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.48it/s]


[[4363   64  774]
 [4281  891 4426]
 [ 642   45 4019]]
0.6129693863983441 0.47541655985644704 0.85401614959626 0.8388771390117286


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.29it/s]


[[4518   88  595]
 [4332 1009 4257]
 [ 780   79 3847]]
0.611346137254758 0.4805947193027429 0.8174670633234169 0.8686791001730436


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.32it/s]


[[4490   70  641]
 [4382  977 4239]
 [ 726  100 3880]]
0.6096586741899189 0.47921045885670344 0.8244793880152996 0.8632955200922899


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.52it/s]


[[4627   56  518]
 [4537  854 4207]
 [ 873   62 3771]]
0.60724129174885 0.4743399128428608 0.8013174670633234 0.8896366083445492


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.59it/s]


[[4536  102  563]
 [4331 1067 4200]
 [ 799   99 3808]]
0.6046684594978964 0.48249166880287103 0.8091797705057373 0.8721399730820996


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.26it/s]


[[4493   84  624]
 [4308 1029 4261]
 [ 781   88 3837]]
0.6026226954352587 0.47982568572160983 0.8153421164470889 0.8638723322437992


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.80it/s]


[[4524   89  588]
 [4399 1063 4136]
 [ 820  105 3781]]
0.6006275657424354 0.48028710587028967 0.8034424139396515 0.8698327244760623


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.43it/s]


[[4466  152  583]
 [4184 1339 4075]
 [ 779  162 3765]]
0.5973829483627376 0.4906434247628813 0.8000424989375265 0.8586810228802153


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.56it/s]


[[4546   88  567]
 [4416 1007 4175]
 [ 843   96 3767]]
0.5953338854294971 0.4778261984106639 0.8004674883127921 0.8740626802537973


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.84it/s]


[[4595   84  522]
 [4454 1034 4110]
 [ 865  100 3741]]
0.5916881525426879 0.4803896436811074 0.7949426264343391 0.8834839453951163


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.39it/s]


[[4492  113  596]
 [4340 1157 4101]
 [ 795  136 3775]]
0.5886930608211604 0.4831581645731864 0.8021674458138547 0.8636800615266295


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.29it/s]


[[4539   98  564]
 [4372 1109 4117]
 [ 877  115 3714]]
0.5854589087622506 0.47997949243783644 0.7892052698682533 0.872716785233609


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.93it/s]


[[4477  103  621]
 [4342 1162 4094]
 [ 785  143 3778]]
0.5817908223410299 0.48279928223532426 0.8028049298767531 0.8607960007690829


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.32it/s]


[[4338  137  726]
 [4224 1226 4148]
 [ 697  133 3876]]
0.5785577875330932 0.4839784670597283 0.8236294092647684 0.8340703710824842


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.91it/s]


[[4411  137  653]
 [4228 1125 4245]
 [ 767  107 3832]]
0.5744353353529048 0.48028710587028967 0.8142796430089247 0.8481061334358777


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.22it/s]


[[4484  146  571]
 [4355 1238 4005]
 [ 875  155 3676]]
0.5707160104486279 0.48182517303255573 0.7811304717382066 0.8621418957892713


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.50it/s]


[[4392  157  652]
 [4196 1360 4042]
 [ 781  172 3753]]
0.5655419521762016 0.4873109459113048 0.7974925626859328 0.844452989809652


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.71it/s]


[[4412  155  634]
 [4237 1270 4091]
 [ 792  149 3765]]
0.5621906232116813 0.4843373493975904 0.8000424989375265 0.8482984041530475


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.61it/s]


[[4270  167  764]
 [4141 1237 4220]
 [ 739  140 3827]]
0.5579979728935356 0.4785439630863881 0.8132171695707607 0.8209959623149394


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.97it/s]


[[4290  163  748]
 [4118 1296 4184]
 [ 715  153 3838]]
0.5521130557347061 0.4831581645731864 0.8155546111347216 0.8248413766583349


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.05it/s]


[[4325  179  697]
 [4214 1393 3991]
 [ 799  223 3684]]
0.5464531169798141 0.48203024865419125 0.782830429239269 0.831570851759277


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.86it/s]


[[4248  209  744]
 [4026 1343 4229]
 [ 739  161 3806]]
0.5412894317081997 0.4817739041271469 0.8087547811304717 0.8167660065372044


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.31it/s]


[[4351  193  657]
 [4218 1430 3950]
 [ 828  235 3643]]
0.5351133198666393 0.4831581645731864 0.7741181470463239 0.8365698904056912


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.30it/s]


[[4224  219  758]
 [4091 1389 4118]
 [ 770  182 3754]]
0.5310157398532208 0.4802358369648808 0.7977050573735657 0.8121515093251298


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.37it/s]


[[4310  213  678]
 [4191 1427 3980]
 [ 808  234 3664]]
0.5249728668004947 0.48197897974878234 0.7785805354866129 0.8286867910017305


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.31it/s]


[[4193  288  720]
 [4061 1567 3970]
 [ 763  274 3669]]
0.5188597568443843 0.4834145091002307 0.7796430089247769 0.8061911170928667


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.37it/s]


[[4131  323  747]
 [3977 1508 4113]
 [ 740  192 3774]]
0.5128049238731986 0.4825942066136888 0.8019549511262218 0.7942703326283407


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.10it/s]


[[4137  330  734]
 [4064 1628 3906]
 [ 779  280 3647]]
0.5069443785158315 0.48254293770827994 0.774968125796855 0.7954239569313594


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.36it/s]


[[4218  295  688]
 [4061 1432 4105]
 [ 838  207 3661]]
0.50151749123308 0.4773647782619841 0.7779430514237144 0.8109978850221111


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.34it/s]


[[3926  476  799]
 [3767 1838 3993]
 [ 719  282 3705]]
0.49530259671067833 0.4854652653165855 0.787292817679558 0.7548548356085368


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.67it/s]


[[4003  411  787]
 [3881 1690 4027]
 [ 729  257 3720]]
0.48785600559155745 0.4825942066136888 0.7904802379940501 0.7696596808306095


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.31it/s]


[[4137  337  727]
 [4059 1774 3765]
 [ 799  383 3524]]
0.48291255612122386 0.48372212253268393 0.7488312792180195 0.7954239569313594


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.10it/s]


[[3991  445  765]
 [3871 1876 3851]
 [ 792  338 3576]]
0.476551045600633 0.48413227377595486 0.7598810029749257 0.7673524322245722


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.29it/s]


[[4016  420  765]
 [3907 1798 3893]
 [ 795  302 3609]]
0.4704478094004151 0.4831068956677775 0.7668933276668083 0.7721592001538166


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.98it/s]


[[4119  380  702]
 [4037 1924 3637]
 [ 837  415 3454]]
0.46415627809395466 0.4869007946680338 0.7339566510837229 0.7919630840223034


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.51it/s]


[[3952  434  815]
 [3882 1816 3900]
 [ 784  326 3596]]
0.45542328384585845 0.4800820302486542 0.7641308967275818 0.759853874254951


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.22it/s]


[[3807  518  876]
 [3667 1984 3947]
 [ 708  375 3623]]
0.45010251591080114 0.48264547551909764 0.7698682532936677 0.7319746202653336


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.42it/s]


[[3823  553  825]
 [3668 2122 3808]
 [ 701  422 3583]]
0.44491217234977204 0.4884901307357088 0.7613684657883553 0.73505095174005


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.16it/s]


[[3790  572  839]
 [3586 2206 3806]
 [ 711  460 3535]]
0.43834543810751203 0.4886439374519354 0.7511687207819805 0.7287060180734474


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.46it/s]


[[3975  492  734]
 [3816 2304 3478]
 [ 821  583 3302]]
0.43331350890317355 0.4912073827223789 0.7016574585635359 0.7642761007498557


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.24it/s]


[[3796  588  817]
 [3679 2258 3661]
 [ 741  459 3506]]
0.4286137147057325 0.4901307357087926 0.745006374840629 0.7298596423764661


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.34it/s]


[[3897  566  738]
 [3738 2208 3652]
 [ 802  506 3398]]
0.42083105131199483 0.48720840810048704 0.7220569485762856 0.7492789848106134


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.28it/s]


[[3516  818  867]
 [3281 2546 3771]
 [ 677  481 3548]]
0.4157006019040158 0.4926941809792361 0.753931151721207 0.676023841568929


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.85it/s]


[[3630  721  850]
 [3423 2525 3650]
 [ 693  544 3469]]
0.41003576145136267 0.49341194565496027 0.737144071398215 0.6979427033262834


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.95it/s]


[[3746  720  735]
 [3514 2552 3532]
 [ 789  568 3349]]
0.40446996599211726 0.49459113047936426 0.7116447088822779 0.7202461065179773


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.86it/s]


[[3473  911  817]
 [3129 2835 3634]
 [ 704  565 3437]]
0.398622711350147 0.4996154832094335 0.7303442413939651 0.6677562007306287


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.75it/s]


[[3739  695  767]
 [3495 2566 3537]
 [ 768  613 3325]]
0.39471731262099474 0.4937195590874135 0.7065448363790905 0.7189002114977889


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.85it/s]


[[3867  654  680]
 [3589 2687 3322]
 [ 789  739 3178]]
0.38821713413511005 0.4989489874391182 0.6753081172970675 0.7435108632955201


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.22it/s]


[[3748  698  755]
 [3487 2714 3397]
 [ 758  706 3242]]
0.38368164596701027 0.49751345808766984 0.6889077773055674 0.7206306479523169


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.94it/s]


[[3685  789  727]
 [3405 2748 3445]
 [ 751  665 3290]]
0.3766144543213952 0.49848756729043836 0.6991075223119422 0.708517592770621


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.46it/s]


[[3505  856  840]
 [3176 2937 3485]
 [ 696  680 3330]]
0.3744299664981383 0.500999743655473 0.7076073098172546 0.6739088636800615


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.14it/s]


[[3628  817  756]
 [3291 2879 3428]
 [ 738  727 3241]]
0.37026648346642804 0.4997692899256601 0.6886952826179346 0.6975581618919439


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.09it/s]


[[3652  842  707]
 [3320 2828 3450]
 [ 774  677 3255]]
0.36272778770977393 0.4991027941553448 0.6916702082447939 0.7021726591040185


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.28it/s]


[[3455  957  789]
 [3147 2922 3529]
 [ 695  672 3339]]
0.35834181734493803 0.4981286849525763 0.7095197620059499 0.6642953278215727


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.95it/s]


[[3415 1027  759]
 [3031 3156 3411]
 [ 709  784 3213]]
0.35227892407797334 0.5016149705203794 0.682745431364216 0.6566044991347818


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.77it/s]


[[3452  980  769]
 [3113 3080 3405]
 [ 734  756 3216]]
0.35149205582482473 0.4997692899256601 0.6833829154271143 0.6637185156700635


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.16it/s]


[[3500  943  758]
 [3199 3226 3173]
 [ 714  943 3049]]
0.3466532342416003 0.5011535503716996 0.6478963025924351 0.6729475100942126


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.97it/s]


[[3459  997  745]
 [3091 3235 3272]
 [ 702  876 3128]]
0.3428893380595329 0.5035631889259164 0.6646833829154272 0.6650644106902519


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.95it/s]


[[3448 1032  721]
 [3082 3193 3323]
 [ 719  811 3176]]
0.3359740634161727 0.5033068443988721 0.6748831279218019 0.6629494328013843


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.74it/s]


[[3539  942  720]
 [3166 3112 3320]
 [ 741  808 3157]]
0.3329692644284184 0.5028454242501923 0.6708457288567786 0.6804460680638339


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.79it/s]


[[3386 1076  739]
 [3020 3339 3239]
 [ 739  889 3078]]
0.33014883941277523 0.5025890797231479 0.6540586485337867 0.6510286483368583


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.58it/s]


[[3399 1068  734]
 [3008 3370 3220]
 [ 720  930 3056]]
0.32396331989675536 0.503716995642143 0.6493837654058648 0.6535281676600654


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.00it/s]


[[3378 1069  754]
 [2969 3348 3281]
 [ 725  868 3113]]
0.3217643035533733 0.5044347603178672 0.661495962600935 0.6494904825995


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.97it/s]


[[3373 1058  770]
 [2931 3404 3263]
 [ 699  919 3088]]
0.31920498766397176 0.5057677518584979 0.6561835954101147 0.6485291290136512


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.55it/s]


[[3412 1081  708]
 [3018 3515 3065]
 [ 734  988 2984]]
0.3150884910185534 0.5081261215073059 0.6340841478963026 0.6560276869832724


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.23it/s]


[[3403 1113  685]
 [3012 3745 2841]
 [ 746 1165 2795]]
0.31133119930002023 0.5097667264803897 0.5939226519337016 0.6542972505287444


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.40it/s]


[[3398 1094  709]
 [3030 3504 3064]
 [ 748 1012 2946]]
0.3085468608633916 0.504896180466547 0.6260093497662559 0.6533358969428956


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.61it/s]


[[3252 1242  707]
 [2795 3947 2856]
 [ 706 1154 2846]]
0.30329458650789765 0.5149961548320944 0.604759881002975 0.6252643722361084


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.70it/s]


[[3364 1134  703]
 [2937 3651 3010]
 [ 712 1064 2930]]
0.30060644044463797 0.5098692642912074 0.6226094347641309 0.6467986925591233


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.48it/s]


[[3256 1250  695]
 [2828 3766 3004]
 [ 734 1050 2922]]
0.29623613904293317 0.5098179953857985 0.6209094772630684 0.6260334551047876


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.96it/s]


[[3170 1317  714]
 [2721 4031 2846]
 [ 681 1185 2840]]
0.2938993234831588 0.5147910792104589 0.6034849128771781 0.6094981734281869


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  4.77it/s]


[[3325 1179  697]
 [2866 3718 3014]
 [ 727 1045 2934]]
0.29355760848611817 0.5115098692642912 0.6234594135146622 0.639300134589502


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.55it/s]


[[3335 1191  675]
 [2873 3753 2972]
 [ 730 1074 2902]]
0.28629718967398304 0.5121763650346065 0.6166595835104123 0.6412228417611998


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.55it/s]


[[3158 1304  739]
 [2741 3841 3016]
 [ 690 1072 2944]]
0.28289037797235905 0.5097667264803897 0.6255843603909902 0.6071909248221495


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.56it/s]


[[3192 1306  703]
 [2728 3771 3099]
 [ 718  990 2998]]
0.28525768724599276 0.5106895667777493 0.6370590735231619 0.6137281292059219


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.59it/s]


[[3242 1258  701]
 [2812 3948 2838]
 [ 720 1161 2825]]
0.28013556310556886 0.5134580876698283 0.6002974925626859 0.6233416650644107


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.56it/s]


[[3287 1215  699]
 [2848 3837 2913]
 [ 707 1126 2873]]
0.2761672318429875 0.5125352473724686 0.6104972375690608 0.6319938473370506


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.27it/s]


[[3267 1217  717]
 [2856 3964 2778]
 [ 711 1228 2767]]
0.2728271938132164 0.5125865162778774 0.587972800679983 0.6281484329936551


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.14it/s]


[[3081 1390  730]
 [2597 4080 2921]
 [ 681 1145 2880]]
0.2728371608974342 0.5147910792104589 0.6119847003824904 0.5923860796000769


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.26it/s]


[[3267 1262  672]
 [2832 4067 2699]
 [ 746 1244 2716]]
0.267287988859908 0.5152524993591386 0.5771355716107097 0.6281484329936551


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.51it/s]


[[3064 1419  718]
 [2559 4174 2865]
 [ 661 1226 2819]]
0.26421164726852475 0.5156113816970007 0.5990225244368891 0.5891174774081908


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.44it/s]


[[3103 1372  726]
 [2640 4141 2817]
 [ 661 1226 2819]]
0.26472718352661995 0.5159189951294539 0.5990225244368891 0.5966160353778119


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.49it/s]


[[3250 1285  666]
 [2782 4198 2618]
 [ 742 1321 2643]]
0.2590915690687366 0.5173545244809024 0.5616234594135147 0.6248798308017689


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.29it/s]


[[3128 1388  685]
 [2615 4216 2767]
 [ 694 1243 2769]]
0.25186172665509965 0.5184824403998974 0.5883977900552486 0.6014228033070563


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.57it/s]


[[3088 1396  717]
 [2630 4225 2743]
 [ 675 1272 2759]]
0.2529436060808655 0.5163804152781338 0.5862728431789205 0.5937319746202653


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.31it/s]


[[3068 1425  708]
 [2611 4289 2698]
 [ 696 1273 2737]]
0.25625285562267874 0.5175083311971289 0.5815979600509987 0.5898865602768698


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.82it/s]


[[3186 1369  646]
 [2743 4181 2674]
 [ 757 1293 2656]]
0.25439249561693433 0.5138682389130992 0.5643858903527412 0.6125745049029033


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.22it/s]


[[3011 1482  708]
 [2507 4375 2716]
 [ 697 1261 2748]]
0.24759042431089215 0.5195590874134837 0.5839354016149596 0.5789271293981927


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.88it/s]


[[3131 1419  651]
 [2647 4483 2468]
 [ 696 1452 2558]]
0.24452569038796246 0.5215073058190207 0.5435614109647259 0.6019996154585656


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  6.79it/s]


[[3108 1416  677]
 [2645 4260 2693]
 [ 686 1279 2741]]
0.24699811178042477 0.518277364778262 0.58244793880153 0.5975773889636609


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.15it/s]


[[3115 1416  670]
 [2615 4425 2558]
 [ 698 1390 2618]]
0.24512874900846554 0.5207895411432966 0.5563110922226945 0.5989232839838493


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.00it/s]


[[2963 1514  724]
 [2471 4512 2615]
 [ 659 1397 2650]]
0.23761552000852457 0.5190976672648039 0.5631109222269444 0.5696981349740434


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  6.98it/s]


[[2943 1556  702]
 [2435 4547 2616]
 [ 667 1376 2663]]
0.23572753896390586 0.5205331966162522 0.5658733531661708 0.565852720630648


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.03it/s]


[[2912 1597  692]
 [2368 4594 2636]
 [ 661 1370 2675]]
0.2324934965909872 0.5219687259677006 0.5684232894177645 0.5598923283983849


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.03it/s]


[[2986 1515  700]
 [2473 4519 2606]
 [ 644 1422 2640]]
0.22785137055959917 0.5201230453729813 0.5609859753506162 0.5741203614689483


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.40it/s]


[[3074 1475  652]
 [2601 4456 2541]
 [ 714 1419 2573]]
0.22857709072138133 0.5179697513458088 0.546748831279218 0.5910401845798885


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.43it/s]


[[3006 1514  681]
 [2501 4569 2528]
 [ 687 1443 2576]]
0.22762108039587065 0.5204306588054345 0.5473863153421165 0.5779657758123438


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.13it/s]


[[3109 1419  673]
 [2642 4696 2260]
 [ 705 1589 2412]]
0.23185988566032925 0.5238144065624198 0.5125371865703358 0.5977696596808306


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.40it/s]


[[2940 1553  708]
 [2468 4489 2641]
 [ 660 1366 2680]]
0.23449143666521946 0.518277364778262 0.5694857628559286 0.5652759084791387


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.27it/s]


[[3082 1465  654]
 [2607 4512 2479]
 [ 725 1448 2533]]
0.2289508152052872 0.5192002050756216 0.5382490437739057 0.5925783503172467


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.30it/s]


[[2929 1550  722]
 [2462 4477 2659]
 [ 669 1370 2667]]
0.21819398356111427 0.5164316841835427 0.5667233319167021 0.5631609305902711


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.10it/s]


[[2983 1557  661]
 [2470 4602 2526]
 [ 700 1419 2587]]
0.21196753234791577 0.5215073058190207 0.5497237569060773 0.573543549317439


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.06it/s]


[[3092 1456  653]
 [2601 4400 2597]
 [ 716 1393 2597]]
0.21172679658222915 0.5172519866700845 0.5518487037824055 0.5945010574889444


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.10it/s]


[[2877 1631  693]
 [2369 4711 2518]
 [ 670 1471 2565]]
0.21340087515519077 0.5205331966162522 0.5450488737781556 0.5531628532974427


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:04<00:00,  6.73it/s]


[[2874 1633  694]
 [2385 4659 2554]
 [ 660 1427 2619]]
0.2213581547253114 0.5204819277108433 0.5565235869103272 0.5525860411459335


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.38it/s]


[[2905 1596  700]
 [2399 4753 2446]
 [ 657 1489 2560]]
0.21515350671190964 0.5238656754678288 0.5439864003399915 0.5585464333781965


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.07it/s]


[[2887 1659  655]
 [2378 4783 2437]
 [ 678 1496 2532]]
0.20828101543107427 0.5230453729812868 0.5380365490862729 0.5550855604691406


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.03it/s]


[[2905 1616  680]
 [2402 4729 2467]
 [ 684 1475 2547]]
0.20838446870334165 0.5219687259677006 0.541223969400765 0.5585464333781965


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.95it/s]


[[2943 1607  651]
 [2449 4766 2383]
 [ 687 1559 2460]]
0.2012527959239214 0.5213534991027942 0.5227369315767105 0.565852720630648


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.97it/s]


[[2844 1650  707]
 [2403 4706 2489]
 [ 657 1447 2602]]
0.1962824270017165 0.5204819277108433 0.5529111772205695 0.5468179196308403


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.01it/s]


[[2882 1610  709]
 [2402 4596 2600]
 [ 664 1377 2665]]
0.19658856474815456 0.5200205075621636 0.5662983425414365 0.5541242068832917


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:06<00:00,  5.42it/s]


[[2948 1578  675]
 [2434 4747 2417]
 [ 663 1529 2514]]
0.19834074254770925 0.5234042553191489 0.5342116447088823 0.5668140742164969


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.50it/s]


[[2976 1546  679]
 [2500 4762 2336]
 [ 697 1576 2433]]
0.19207146203607545 0.5214560369136119 0.5169995750106248 0.5721976542972506


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.66it/s]


[[2913 1593  695]
 [2428 4528 2642]
 [ 659 1312 2735]]
0.20057473202845208 0.5217123814406562 0.5811729706757331 0.5600845991155547


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.95it/s]


[[2877 1642  682]
 [2372 4741 2485]
 [ 661 1473 2572]]
0.208394885287249 0.5224301461163804 0.5465363365915852 0.5531628532974427


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.94it/s]


[[2919 1600  682]
 [2441 4718 2439]
 [ 670 1543 2493]]
0.21101968472165272 0.5193540117918483 0.5297492562685933 0.5612382234185733


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.95it/s]


[[2797 1703  701]
 [2327 4852 2419]
 [ 619 1539 2548]]
0.1943086934717078 0.5227890284542425 0.5414364640883977 0.5377811959238608


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.85it/s]


[[2860 1665  676]
 [2331 4850 2417]
 [ 675 1535 2496]]
0.18587615850724673 0.5232504486029224 0.5303867403314917 0.5498942511055567


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.95it/s]


[[2813 1703  685]
 [2282 4901 2415]
 [ 637 1562 2507]]
0.17700964694184468 0.5240194821840554 0.5327241818954526 0.5408575273985772


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.01it/s]


[[2828 1683  690]
 [2337 4812 2449]
 [ 652 1531 2523]]
0.17954778828118978 0.5210458856703409 0.5361240968975776 0.5437415881561238


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.98it/s]


[[2818 1718  665]
 [2340 5011 2247]
 [ 655 1655 2396]]
0.1826161326546418 0.5242245578056909 0.5091372715682108 0.5418188809844261


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.81it/s]


[[2810 1721  670]
 [2355 4966 2277]
 [ 666 1643 2397]]
0.18086721361579752 0.5215585747244297 0.5093497662558436 0.5402807152470679


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.01it/s]


[[2876 1661  664]
 [2408 4842 2348]
 [ 676 1608 2422]]
0.17645442418586044 0.5198667008459369 0.5146621334466638 0.552970582580273


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.88it/s]


[[2760 1754  687]
 [2236 4939 2423]
 [ 642 1543 2521]]
0.17442800877685832 0.5239682132786465 0.535699107522312 0.5306671793885791


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.00it/s]


[[2907 1642  652]
 [2410 4864 2324]
 [ 690 1600 2416]]
0.1765496781221906 0.5222763394001538 0.513387165320867 0.5589309748125361


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.78it/s]


[[2738 1789  674]
 [2254 4974 2370]
 [ 646 1559 2501]]
0.17743522522592903 0.5236093309407844 0.5314492137696557 0.5264372236108441


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.17it/s]


[[2823 1715  663]
 [2314 4930 2354]
 [ 645 1607 2454]]
0.18392657684652428 0.5233017175083312 0.5214619634509138 0.5427802345702749


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  5.91it/s]


[[2839 1706  656]
 [2378 4953 2267]
 [ 670 1633 2403]]
0.18581863565552503 0.5226864906434248 0.5106247343816405 0.5458565660449913


100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:05<00:00,  6.05it/s]


[[2737 1779  685]
 [2241 5048 2309]
 [ 623 1639 2444]]
0.1760162098291225 0.5244296334273263 0.5193370165745856 0.5262449528936743


 65%|████████████████████████████████████████████████████▉                            | 87/133 [00:32<00:15,  2.91it/s]

In [ ]:
df_test = df_an[['time', 'open', 'high', 'low', 'close','TP','SL','pivots_l','pivots_h']].iloc[indeces_test[0]:].copy()
df_test['SIGNAL'] = 0
for i,idx in enumerate(indeces_test):
    if i > 0:
#         df_test.SIGNAL.loc[idx] = y_perdict[i]
        if df_test.pivots_l[idx-1]==1 and y_perdict[i] ==BUY:
            df_test.SIGNAL.loc[idx] = y_perdict[i]-1
        if df_test.pivots_h[idx-1]==1 and y_perdict[i] ==SELL:
            df_test.SIGNAL.loc[idx] = y_perdict[i]-1

df_test.reset_index(drop=True, inplace=True)

In [ ]:
gt = GuruTester2(
        df_test,
        df_m5,
        SPREAD,
        use_spread=True
    )
df_res_m5 = gt.run_test()

In [ ]:
df_res_m5['balance'] = 100
loss_margin = 0.03
perv_balance = 100

# for index, row in df_res_m5.iterrows():
for i in range(len(df_res_m5)):
    if(df_res_m5.result[i] == -1):
        loss_ratio =1# abs( (df_res_m5['start_price'][i]-df_res_m5['trigger_price'][i])/((df_res_m5['start_price'][i]-df_res_m5['SL'][i])) )
#         print(loss_ratio)
        df_res_m5['balance'][i] = perv_balance*(1-loss_ratio*loss_margin) 
    elif(df_res_m5.result[i] == 2):
        profit_to_loss = 2#abs( (df_res_m5['start_price'][i]-df_res_m5['trigger_price'][i])/((df_res_m5['start_price'][i]-df_res_m5['SL'][i])) )
#         print(profit_to_loss)
        df_res_m5['balance'][i] = perv_balance*(1+profit_to_loss*loss_margin) 
    perv_balance = df_res_m5['balance'][i]

In [ ]:
df_res_m5_plot = df_res_m5#.loc[:100]
df_res_m5_plot['time'] = df_res_m5_plot['end_time']
cp = CandlePlot(df_res_m5_plot, candles=False)
print("min balance ",min(df_res_m5['balance']))
cp.show_plot(line_traces=['balance'])